apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base # 기본 매니페스트 장소

images:
  - name: backend-app-image # 여기는 변경하지 않는다.
    newTag: x.x.x # 애플리케이션 버전 번호
    newName: <Your_registry_URI> # ECR 레지스트리 URI
